### ISSUE TITLE
Error en el campo de visión del Agente de Seguridad

### ISSUE THREAD

**Issue by admont02** [Proyectos1-FDI-UCM/c2021-Grupo05#4]
% Errores encontrados: 1
% Adrián Montero Castrillo
% 25-05-2021

### Descripción

A lo largo del nivel, nos encontramos numerosos enemigos de este tipo (Agente de Seguridad), la mayoría de ellos funcionan correctamente, sin embargo, algunos (todos ubicados en las zonas finales del nivel,tras pasar la zona de láseres), presentan errores en su campo de visión. Estos errores consisten en algunos casos, en la aparición intermitente de su campo de visión, y en otros casos directamente el ya mencionado campo de visión nunca aparece, por lo que eres indetectable.
![WhatsApp Image 2021-05-25 at 10 53 36](https://user-images.githubusercontent.com/82326212/119474809-d7c35900-bd4c-11eb-9416-ddb4e9a7ce7f.jpeg)

### Pasos 

Pasos seguidos para poder reproducir el error:
1. Desde el menú principal, iniciamos una nueva partida.

2. Una vez en el nivel , avanzamos en él hasta pasar la zona en la que se encuentran los láseres.

3. Hacemos blink y entramos en la siguiente sala, a partir de aquí, nos comenzamos a fijar en todos los Agentes de Seguridad.

### Captura de pantalla o vídeo

[Vídeo donde se ve el error](https://www.youtube.com/watch?v=87pYb9s-KNA)

**Comment by Edu-git1** [comment]
Añadiendo a lo que mi compañero ya ha descrito, en mis ejecuciones también le ha desaparecido el campo de visión a uno de los doberman. Además, parece que desaparece con más frecuencia cuando los enemigos se encuentran cerca de los extremos de la pantalla. No pasa con todos los enemigos
